export { default as LandingPage } from "./LandingPage";
export { default as SigninPage } from "./SigninPage";
export { default as SignupPage } from "./SignupPage";
export { default as ResetPassword } from "./ResetPassword";
export { default as ResetPasswordConfirm } from "./ResetPasswordConfirm";
export { default as OTPAuth } from "./OTPAuths"
export { default as SuccessPage } from "./SuccessPage";
export { default as Dashboard } from "./Dashboard";
export { default as Settings } from "./Settings";
export { default as DashboardHome } from "./DashboardHome";
export { default as Chats } from "./Chats";